<!DOCTYPE html>
<html>
    <head>
        <script defer src="./js/index.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <meta charset="utf-8"/>
        <title>Shopping List</title>
        <style>

            .container {
                width: 80%;
                margin: 0 auto;
            }

            h1 {
                text-align: center;
                color: #000000;
                font-size: 3rem;
                margin: 30px 0;
            }

            #list, form, #error-message {
                width: 40%;
                margin: 0 auto;
            }

            #error-message {
                color: red;
            }

            #add-item-row {
                width:90%;
            }


        </style>
    </head>
    <body>
    <div class="container">
        <h1>Shopping List</h1>
        <form>
            <div class="form-group">
                <div id="add-item-row" class="row">
                    <div class="col-11">
                        <input id="user-item" type="text" class="form-control" placeholder="Add item">
                    </div>
                    <div class="col-1">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </form>
        <div id="error-message"></div>

        <div id="list">
            <?php require('partials/ItemList.phtml')?>
        </div>
    </div>
    </body>
</html>
